
export interface State {
    name: string;
    code: string;
}

export interface Country {
    code: string;
    name: string;
    stateLabel?: string;
    states?: State[];
}

export const countries: Country[] = [
    { code: 'US', name: 'United States', stateLabel: 'State', states: [
        { name: 'Alabama', code: 'AL' }, { name: 'Alaska', code: 'AK' }, { name: 'Arizona', code: 'AZ' },
        { name: 'Arkansas', code: 'AR' }, { name: 'California', code: 'CA' }, { name: 'Colorado', code: 'CO' },
        { name: 'Connecticut', code: 'CT' }, { name: 'Delaware', code: 'DE' }, { name: 'Florida', code: 'FL' },
        { name: 'Georgia', code: 'GA' }, { name: 'Hawaii', code: 'HI' }, { name: 'Idaho', code: 'ID' },
        { name: 'Illinois', code: 'IL' }, { name: 'Indiana', code: 'IN' }, { name: 'Iowa', code: 'IA' },
        { name: 'Kansas', code: 'KS' }, { name: 'Kentucky', code: 'KY' }, { name: 'Louisiana', code: 'LA' },
        { name: 'Maine', code: 'ME' }, { name: 'Maryland', code: 'MD' }, { name: 'Massachusetts', code: 'MA' },
        { name: 'Michigan', code: 'MI' }, { name: 'Minnesota', code: 'MN' }, { name: 'Mississippi', code: 'MS' },
        { name: 'Missouri', code: 'MO' }, { name: 'Montana', code: 'MT' }, { name: 'Nebraska', code: 'NE' },
        { name: 'Nevada', code: 'NV' }, { name: 'New Hampshire', code: 'NH' }, { name: 'New Jersey', code: 'NJ' },
        { name: 'New Mexico', code: 'NM' }, { name: 'New York', code: 'NY' }, { name: 'North Carolina', code: 'NC' },
        { name: 'North Dakota', code: 'ND' }, { name: 'Ohio', code: 'OH' }, { name: 'Oklahoma', code: 'OK' },
        { name: 'Oregon', code: 'OR' }, { name: 'Pennsylvania', code: 'PA' }, { name: 'Rhode Island', code: 'RI' },
        { name: 'South Carolina', code: 'SC' }, { name: 'South Dakota', code: 'SD' }, { name: 'Tennessee', code: 'TN' },
        { name: 'Texas', code: 'TX' }, { name: 'Utah', code: 'UT' }, { name: 'Vermont', code: 'VT' },
        { name: 'Virginia', code: 'VA' }, { name: 'Washington', code: 'WA' }, { name: 'West Virginia', code: 'WV' },
        { name: 'Wisconsin', code: 'WI' }, { name: 'Wyoming', code: 'WY' }
    ]},
    { code: 'CA', name: 'Canada', stateLabel: 'Province', states: [
        { name: 'Alberta', code: 'AB' }, { name: 'British Columbia', code: 'BC' }, { name: 'Manitoba', code: 'MB' },
        { name: 'New Brunswick', code: 'NB' }, { name: 'Newfoundland and Labrador', code: 'NL' },
        { name: 'Nova Scotia', code: 'NS' }, { name: 'Ontario', code: 'ON' }, { name: 'Prince Edward Island', code: 'PE' },
        { name: 'Quebec', code: 'QC' }, { name: 'Saskatchewan', code: 'SK' }
    ]},
    { code: 'AU', name: 'Australia', stateLabel: 'State/Territory', states: [
        { name: 'Australian Capital Territory', code: 'ACT' }, { name: 'New South Wales', code: 'NSW' },
        { name: 'Northern Territory', code: 'NT' }, { name: 'Queensland', code: 'QLD' },
        { name: 'South Australia', code: 'SA' }, { name: 'Tasmania', code: 'TAS' },
        { name: 'Victoria', code: 'VIC' }, { name: 'Western Australia', code: 'WA' }
    ]},
    { code: 'AF', name: 'Afghanistan' },
    { name: 'AL', name: 'Albania' },
    { name: 'DZ', name: 'Algeria' },
    { name: 'AD', name: 'Andorra' },
    { name: 'AO', name: 'Angola' },
    { name: 'AG', name: 'Antigua and Barbuda' },
    { name: 'AR', name: 'Argentina' },
    { name: 'AM', name: 'Armenia' },
    { name: 'AT', name: 'Austria' },
    { name: 'AZ', name: 'Azerbaijan' },
    { name: 'BS', name: 'Bahamas' },
    { name: 'BH', name: 'Bahrain' },
    { name: 'BD', name: 'Bangladesh' },
    { name: 'BB', name: 'Barbados' },
    { name: 'BY', name: 'Belarus' },
    { name: 'BE', name: 'Belgium' },
    { name: 'BZ', name: 'Belize' },
    { name: 'BJ', name: 'Benin' },
    { name: 'BT', name: 'Bhutan' },
    { name: 'BO', name: 'Bolivia' },
    { name: 'BA', name: 'Bosnia and Herzegovina' },
    { name: 'BW', name: 'Botswana' },
    { name: 'BR', name: 'Brazil' },
    { name: 'BN', name: 'Brunei' },
    { name: 'BG', name: 'Bulgaria' },
    { name: 'BF', name: 'Burkina Faso' },
    { name: 'BI', name: 'Burundi' },
    { name: 'CV', name: 'Cabo Verde' },
    { name: 'KH', name: 'Cambodia' },
    { name: 'CM', name: 'Cameroon' },
    { name: 'CF', name: 'Central African Republic' },
    { name: 'TD', name: 'Chad' },
    { name: 'CL', name: 'Chile' },
    { name: 'CN', name: 'China' },
    { name: 'CO', name: 'Colombia' },
    { name: 'KM', name: 'Comoros' },
    { name: 'CD', name: 'Congo, Democratic Republic of the' },
    { name: 'CG', name: 'Congo, Republic of the' },
    { name: 'CR', name: 'Costa Rica' },
    { name: 'HR', name: 'Croatia' },
    { name: 'CU', name: 'Cuba' },
    { name: 'CY', name: 'Cyprus' },
    { name: 'CZ', name: 'Czech Republic' },
    { name: 'DK', name: 'Denmark' },
    { name: 'DJ', name: 'Djibouti' },
    { name: 'DM', name: 'Dominica' },
    { name: 'DO', name: 'Dominican Republic' },
    { name: 'EC', name: 'Ecuador' },
    { name: 'EG', name: 'Egypt' },
    { name: 'SV', name: 'El Salvador' },
    { name: 'GQ', name: 'Equatorial Guinea' },
    { name: 'ER', name: 'Eritrea' },
    { name: 'EE', name: 'Estonia' },
    { name: 'SZ', name: 'Eswatini' },
    { name: 'ET', name: 'Ethiopia' },
    { name: 'FJ', name: 'Fiji' },
    { name: 'FI', name: 'Finland' },
    { name: 'FR', name: 'France' },
    { name: 'GA', name: 'Gabon' },
    { name: 'GM', name: 'Gambia' },
    { name: 'GE', name: 'Georgia' },
    { name: 'DE', name: 'Germany' },
    { name: 'GH', name: 'Ghana' },
    { name: 'GR', name: 'Greece' },
    { name: 'GD', name: 'Grenada' },
    { name: 'GT', name: 'Guatemala' },
    { name: 'GN', name: 'Guinea' },
    { name: 'GW', name: 'Guinea-Bissau' },
    { name: 'GY', name: 'Guyana' },
    { name: 'HT', name: 'Haiti' },
    { name: 'HN', name: 'Honduras' },
    { name: 'HU', name: 'Hungary' },
    { name: 'IS', name: 'Iceland' },
    { name: 'IN', name: 'India' },
    { name: 'ID', name: 'Indonesia' },
    { name: 'IR', name: 'Iran' },
    { name: 'IQ', name: 'Iraq' },
    { name: 'IE', name: 'Ireland' },
    { name: 'IL', name: 'Israel' },
    { name: 'IT', name: 'Italy' },
    { name: 'JM', name: 'Jamaica' },
    { name: 'JP', name: 'Japan' },
    { name: 'JO', name: 'Jordan' },
    { name: 'KZ', name: 'Kazakhstan' },
    { name: 'KE', name: 'Kenya' },
    { name: 'KI', name: 'Kiribati' },
    { name: 'KW', name: 'Kuwait' },
    { name: 'KG', name: 'Kyrgyzstan' },
    { name: 'LA', name: 'Laos' },
    { name: 'LV', name: 'Latvia' },
    { name: 'LB', name: 'Lebanon' },
    { name: 'LS', name: 'Lesotho' },
    { name: 'LR', name: 'Liberia' },
    { name: 'LY', name: 'Libya' },
    { name: 'LI', name: 'Liechtenstein' },
    { name: 'LT', name: 'Lithuania' },
    { name: 'LU', name: 'Luxembourg' },
    { name: 'MG', name: 'Madagascar' },
    { name: 'MW', name: 'Malawi' },
    { name: 'MY', name: 'Malaysia' },
    { name: 'MV', name: 'Maldives' },
    { name: 'ML', name: 'Mali' },
    { name: 'MT', name: 'Malta' },
    { name: 'MH', name: 'Marshall Islands' },
    { name: 'MR', name: 'Mauritania' },
    { name: 'MU', name: 'Mauritius' },
    { name: 'MX', name: 'Mexico' },
    { name: 'FM', name: 'Micronesia' },
    { name: 'MD', name: 'Moldova' },
    { name: 'MC', name: 'Monaco' },
    { name: 'MN', name: 'Mongolia' },
    { name: 'ME', name: 'Montenegro' },
    { name: 'MA', name: 'Morocco' },
    { name: 'MZ', name: 'Mozambique' },
    { name: 'MM', name: 'Myanmar (Burma)' },
    { name: 'NA', name: 'Namibia' },
    { name: 'NR', name: 'Nauru' },
    { name: 'NP', name: 'Nepal' },
    { name: 'NL', name: 'Netherlands' },
    { name: 'NZ', name: 'New Zealand' },
    { name: 'NI', name: 'Nicaragua' },
    { name: 'NE', name: 'Niger' },
    { name: 'NG', name: 'Nigeria' },
    { name: 'KP', name: 'North Korea' },
    { name: 'MK', name: 'North Macedonia' },
    { name: 'NO', name: 'Norway' },
    { name: 'OM', name: 'Oman' },
    { name: 'PK', name: 'Pakistan' },
    { name: 'PW', name: 'Palau' },
    { name: 'PS', name: 'Palestine State' },
    { name: 'PA', name: 'Panama' },
    { name: 'PG', name: 'Papua New Guinea' },
    { name: 'PY', name: 'Paraguay' },
    { name: 'PE', name: 'Peru' },
    { name: 'PH', name: 'Philippines' },
    { name: 'PL', name: 'Poland' },
    { name: 'PT', name: 'Portugal' },
    { name: 'QA', name: 'Qatar' },
    { name: 'RO', name: 'Romania' },
    { name: 'RU', name: 'Russia' },
    { name: 'RW', name: 'Rwanda' },
    { name: 'KN', name: 'Saint Kitts and Nevis' },
    { name: 'LC', name: 'Saint Lucia' },
    { name: 'VC', name: 'Saint Vincent and the Grenadines' },
    { name: 'WS', name: 'Samoa' },
    { name: 'SM', name: 'San Marino' },
    { name: 'ST', name: 'Sao Tome and Principe' },
    { name: 'SA', name: 'Saudi Arabia' },
    { name: 'SN', name: 'Senegal' },
    { name: 'RS', name: 'Serbia' },
    { name: 'SC', name: 'Seychelles' },
    { name: 'SL', name: 'Sierra Leone' },
    { name: 'SG', name: 'Singapore' },
    { name: 'SK', name: 'Slovakia' },
    { name: 'SI', name: 'Slovenia' },
    { name: 'SB', name: 'Solomon Islands' },
    { name: 'SO', name: 'Somalia' },
    { name: 'ZA', name: 'South Africa' },
    { name: 'KR', name: 'South Korea' },
    { name: 'SS', name: 'South Sudan' },
    { name: 'ES', name: 'Spain' },
    { name: 'LK', name: 'Sri Lanka' },
    { name: 'SD', name: 'Sudan' },
    { name: 'SR', name: 'Suriname' },
    { name: 'SE', name: 'Sweden' },
    { name: 'CH', name: 'Switzerland' },
    { name: 'SY', name: 'Syria' },
    { name: 'TW', name: 'Taiwan' },
    { name: 'TJ', name: 'Tajikistan' },
    { name: 'TZ', name: 'Tanzania' },
    { name: 'TH', name: 'Thailand' },
    { name: 'TL', name: 'Timor-Leste' },
    { name: 'TG', name: 'Togo' },
    { name: 'TO', name: 'Tonga' },
    { name: 'TT', name: 'Trinidad and Tobago' },
    { name: 'TN', name: 'Tunisia' },
    { name: 'TR', name: 'Turkey' },
    { name: 'TM', name: 'Turkmenistan' },
    { name: 'TV', name: 'Tuvalu' },
    { name: 'UG', name: 'Uganda' },
    { name: 'UA', name: 'Ukraine' },
    { name: 'AE', name: 'United Arab Emirates' },
    { name: 'GB', name: 'United Kingdom' },
    { name: 'UY', name: 'Uruguay' },
    { name: 'UZ', name: 'Uzbekistan' },
    { name: 'VU', name: 'Vanuatu' },
    { name: 'VA', name: 'Vatican City' },
    { name: 'VE', name: 'Venezuela' },
    { name: 'VN', name: 'Vietnam' },
    { name: 'YE', name: 'Yemen' },
    { name: 'ZM', name: 'Zambia' },
    { name: 'ZW', name: 'Zimbabwe' },
];
