
export interface State {
    name: string;
    code: string;
}

export interface Country {
    code: string;
    name: string;
    stateLabel?: string;
    states?: State[];
}

export const countries: Country[] = [
    { code: 'US', name: 'United States', stateLabel: 'State', states: [
        { name: 'Alabama', code: 'AL' }, { name: 'Alaska', code: 'AK' }, { name: 'Arizona', code: 'AZ' },
        { name: 'Arkansas', code: 'AR' }, { name: 'California', code: 'CA' }, { name: 'Colorado', code: 'CO' },
        { name: 'Connecticut', code: 'CT' }, { name: 'Delaware', code: 'DE' }, { name: 'Florida', code: 'FL' },
        { name: 'Georgia', code: 'GA' }, { name: 'Hawaii', code: 'HI' }, { name: 'Idaho', code: 'ID' },
        { name: 'Illinois', code: 'IL' }, { name: 'Indiana', code: 'IN' }, { name: 'Iowa', code: 'IA' },
        { name: 'Kansas', code: 'KS' }, { name: 'Kentucky', code: 'KY' }, { name: 'Louisiana', code: 'LA' },
        { name: 'Maine', code: 'ME' }, { name: 'Maryland', code: 'MD' }, { name: 'Massachusetts', code: 'MA' },
        { name: 'Michigan', code: 'MI' }, { name: 'Minnesota', code: 'MN' }, { name: 'Mississippi', code: 'MS' },
        { name: 'Missouri', code: 'MO' }, { name: 'Montana', code: 'MT' }, { name: 'Nebraska', code: 'NE' },
        { name: 'Nevada', code: 'NV' }, { name: 'New Hampshire', code: 'NH' }, { name: 'New Jersey', code: 'NJ' },
        { name: 'New Mexico', code: 'NM' }, { name: 'New York', code: 'NY' }, { name: 'North Carolina', code: 'NC' },
        { name: 'North Dakota', code: 'ND' }, { name: 'Ohio', code: 'OH' }, { name: 'Oklahoma', code: 'OK' },
        { name: 'Oregon', code: 'OR' }, { name: 'Pennsylvania', code: 'PA' }, { name: 'Rhode Island', code: 'RI' },
        { name: 'South Carolina', code: 'SC' }, { name: 'South Dakota', code: 'SD' }, { name: 'Tennessee', code: 'TN' },
        { name: 'Texas', code: 'TX' }, { name: 'Utah', code: 'UT' }, { name: 'Vermont', code: 'VT' },
        { name: 'Virginia', code: 'VA' }, { name: 'Washington', code: 'WA' }, { name: 'West Virginia', code: 'WV' },
        { name: 'Wisconsin', code: 'WI' }, { name: 'Wyoming', code: 'WY' }
    ]},
    { code: 'CA', name: 'Canada', stateLabel: 'Province', states: [
        { name: 'Alberta', code: 'AB' }, { name: 'British Columbia', code: 'BC' }, { name: 'Manitoba', code: 'MB' },
        { name: 'New Brunswick', code: 'NB' }, { name: 'Newfoundland and Labrador', code: 'NL' },
        { name: 'Nova Scotia', code: 'NS' }, { name: 'Ontario', code: 'ON' }, { name: 'Prince Edward Island', code: 'PE' },
        { name: 'Quebec', code: 'QC' }, { name: 'Saskatchewan', code: 'SK' }
    ]},
    { code: 'AU', name: 'Australia', stateLabel: 'State/Territory', states: [
        { name: 'Australian Capital Territory', code: 'ACT' }, { name: 'New South Wales', code: 'NSW' },
        { name: 'Northern Territory', code: 'NT' }, { name: 'Queensland', code: 'QLD' },
        { name: 'South Australia', code: 'SA' }, { name: 'Tasmania', code: 'TAS' },
        { name: 'Victoria', code: 'VIC' }, { name: 'Western Australia', code: 'WA' }
    ]},
    { code: 'DE', name: 'Germany', stateLabel: 'State', states: [
        { name: 'Baden-Württemberg', code: 'BW' }, { name: 'Bavaria', code: 'BY' }, { name: 'Berlin', code: 'BE' },
        { name: 'Brandenburg', code: 'BB' }, { name: 'Bremen', code: 'HB' }, { name: 'Hamburg', code: 'HH' },
        { name: 'Hesse', code: 'HE' }, { name: 'Lower Saxony', code: 'NI' }, { name: 'Mecklenburg-Vorpommern', code: 'MV' },
        { name: 'North Rhine-Westphalia', code: 'NW' }, { name: 'Rhineland-Palatinate', code: 'RP' },
        { name: 'Saarland', code: 'SL' }, { name: 'Saxony', code: 'SN' }, { name: 'Saxony-Anhalt', code: 'ST' },
        { name: 'Schleswig-Holstein', code: 'SH' }, { name: 'Thuringia', code: 'TH' }
    ]},
    { code: 'IN', name: 'India', stateLabel: 'State/Territory', states: [
        { name: 'Andhra Pradesh', code: 'AP' }, { name: 'Arunachal Pradesh', code: 'AR' }, { name: 'Assam', code: 'AS' },
        { name: 'Bihar', code: 'BR' }, { name: 'Chhattisgarh', code: 'CG' }, { name: 'Goa', code: 'GA' },
        { name: 'Gujarat', code: 'GJ' }, { name: 'Haryana', code: 'HR' }, { name: 'Himachal Pradesh', code: 'HP' },
        { name: 'Jharkhand', code: 'JH' }, { name: 'Karnataka', code: 'KA' }, { name: 'Kerala', code: 'KL' },
        { name: 'Madhya Pradesh', code: 'MP' }, { name: 'Maharashtra', code: 'MH' }, { name: 'Manipur', code: 'MN' },
        { name: 'Meghalaya', code: 'ML' }, { name: 'Mizoram', code: 'MZ' }, { name: 'Nagaland', code: 'NL' },
        { name: 'Odisha', code: 'OR' }, { name: 'Punjab', code: 'PB' }, { name: 'Rajasthan', code: 'RJ' },
        { name: 'Sikkim', code: 'SK' }, { name: 'Tamil Nadu', code: 'TN' }, { name: 'Telangana', code: 'TG' },
        { name: 'Tripura', code: 'TR' }, { name: 'Uttar Pradesh', code: 'UP' }, { name: 'Uttarakhand', code: 'UT' },
        { name: 'West Bengal', code: 'WB' }, { name: 'Andaman and Nicobar Islands', code: 'AN' },
        { name: 'Chandigarh', code: 'CH' }, { name: 'Dadra and Nagar Haveli and Daman and Diu', code: 'DN' },
        { name: 'Delhi', code: 'DL' }, { name: 'Jammu and Kashmir', code: 'JK' }, { name: 'Ladakh', code: 'LA' },
        { name: 'Lakshadweep', code: 'LD' }, { name: 'Puducherry', code: 'PY' }
    ]},
    { code: 'BR', name: 'Brazil', stateLabel: 'State', states: [
        { name: 'Acre', code: 'AC' }, { name: 'Alagoas', code: 'AL' }, { name: 'Amapá', code: 'AP' },
        { name: 'Amazonas', code: 'AM' }, { name: 'Bahia', code: 'BA' }, { name: 'Ceará', code: 'CE' },
        { name: 'Espírito Santo', code: 'ES' }, { name: 'Goiás', code: 'GO' }, { name: 'Maranhão', code: 'MA' },
        { name: 'Mato Grosso', code: 'MT' }, { name: 'Mato Grosso do Sul', code: 'MS' },
        { name: 'Minas Gerais', code: 'MG' }, { name: 'Pará', code: 'PA' }, { name: 'Paraíba', code: 'PB' },
        { name: 'Paraná', code: 'PR' }, { name: 'Pernambuco', code: 'PE' }, { name: 'Piauí', code: 'PI' },
        { name: 'Rio de Janeiro', code: 'RJ' }, { name: 'Rio Grande do Norte', code: 'RN' },
        { name: 'Rio Grande do Sul', code: 'RS' }, { name: 'Rondônia', code: 'RO' }, { name: 'Roraima', code: 'RR' },
        { name: 'Santa Catarina', code: 'SC' }, { name: 'São Paulo', code: 'SP' }, { name: 'Sergipe', code: 'SE' },
        { name: 'Tocantins', code: 'TO' }, { name: 'Distrito Federal', code: 'DF' }
    ]},
    { code: 'MX', name: 'Mexico', stateLabel: 'State', states: [
        { name: 'Aguascalientes', code: 'AGS' }, { name: 'Baja California', code: 'BC' },
        { name: 'Baja California Sur', code: 'BCS' }, { name: 'Campeche', code: 'CAMP' },
        { name: 'Chiapas', code: 'CHIS' }, { name: 'Chihuahua', code: 'CHIH' },
        { name: 'Coahuila', code: 'COAH' }, { name: 'Colima', code: 'COL' },
        { name: 'Durango', code: 'DGO' }, { name: 'Guanajuato', code: 'GTO' },
        { name: 'Guerrero', code: 'GRO' }, { name: 'Hidalgo', code: 'HGO' },
        { name: 'Jalisco', code: 'JAL' }, { name: 'México', code: 'MEX' },
        { name: 'Mexico City', code: 'CDMX' }, { name: 'Michoacán', code: 'MICH' },
        { name: 'Morelos', code: 'MOR' }, { name: 'Nayarit', code: 'NAY' },
        { name: 'Nuevo León', code: 'NL' }, { name: 'Oaxaca', code: 'OAX' },
        { name: 'Puebla', code: 'PUE' }, { name: 'Querétaro', code: 'QRO' },
        { name: 'Quintana Roo', code: 'QROO' }, { name: 'San Luis Potosí', code: 'SLP' },
        { name: 'Sinaloa', code: 'SIN' }, { name: 'Sonora', code: 'SON' },
        { name: 'Tabasco', code: 'TAB' }, { name: 'Tamaulipas', code: 'TAMPS' },
        { name: 'Tlaxcala', code: 'TLAX' }, { name: 'Veracruz', code: 'VER' },
        { name: 'Yucatán', code: 'YUC' }, { name: 'Zacatecas', code: 'ZAC' }
    ]},
    { code: 'CN', name: 'China', stateLabel: 'Province', states: [
        { name: 'Anhui', code: 'AH' }, { name: 'Beijing', code: 'BJ' }, { name: 'Chongqing', code: 'CQ' },
        { name: 'Fujian', code: 'FJ' }, { name: 'Gansu', code: 'GS' }, { name: 'Guangdong', code: 'GD' },
        { name: 'Guangxi', code: 'GX' }, { name: 'Guizhou', code: 'GZ' }, { name: 'Hainan', code: 'HI' },
        { name: 'Hebei', code: 'HE' }, { name: 'Heilongjiang', code: 'HL' }, { name: 'Henan', code: 'HA' },
        { name: 'Hong Kong', code: 'HK' }, { name: 'Hubei', code: 'HB' }, { name: 'Hunan', code: 'HN' },
        { name: 'Inner Mongolia', code: 'NM' }, { name: 'Jiangsu', code: 'JS' }, { name: 'Jiangxi', code: 'JX' },
        { name: 'Jilin', code: 'JL' }, { name: 'Liaoning', code: 'LN' }, { name: 'Macau', code: 'MO' },
        { name: 'Ningxia', code: 'NX' }, { name: 'Qinghai', code: 'QH' }, { name: 'Shaanxi', code: 'SN' },
        { name: 'Shandong', code: 'SD' }, { name: 'Shanghai', code: 'SH' }, { name: 'Shanxi', code: 'SX' },
        { name: 'Sichuan', code: 'SC' }, { name: 'Tianjin', code: 'TJ' }, { name: 'Tibet', code: 'XZ' },
        { name: 'Xinjiang', code: 'XJ' }, { name: 'Yunnan', code: 'YN' }, { name: 'Zhejiang', code: 'ZJ' }
    ]},
    { code: 'AR', name: 'Argentina', stateLabel: 'Province', states: [
        { name: 'Buenos Aires', code: 'B' }, { name: 'Buenos Aires F.D.', code: 'C' },
        { name: 'Catamarca', code: 'K' }, { name: 'Chaco', code: 'H' }, { name: 'Chubut', code: 'U' },
        { name: 'Córdoba', code: 'X' }, { name: 'Corrientes', code: 'W' }, { name: 'Entre Ríos', code: 'E' },
        { name: 'Formosa', code: 'P' }, { name: 'Jujuy', code: 'Y' }, { name: 'La Pampa', code: 'L' },
        { name: 'La Rioja', code: 'F' }, { name: 'Mendoza', code: 'M' }, { name: 'Misiones', code: 'N' },
        { name: 'Neuquén', code: 'Q' }, { name: 'Río Negro', code: 'R' }, { name: 'Salta', code: 'A' },
        { name: 'San Juan', code: 'J' }, { name: 'San Luis', code: 'D' }, { name: 'Santa Cruz', code: 'Z' },
        { name: 'Santa Fe', code: 'S' }, { name: 'Santiago del Estero', code: 'G' },
        { name: 'Tierra del Fuego', code: 'V' }, { name: 'Tucumán', code: 'T' }
    ]},
    { code: 'AF', name: 'Afghanistan' },
    { name: 'AL', name: 'Albania' },
    { name: 'DZ', name: 'Algeria' },
    { name: 'AD', name: 'Andorra' },
    { name: 'AO', name: 'Angola' },
    { name: 'AG', name: 'Antigua and Barbuda' },
    { name: 'AM', name: 'Armenia' },
    { name: 'AT', name: 'Austria' },
    { name: 'AZ', name: 'Azerbaijan' },
    { name: 'BS', name: 'Bahamas' },
    { name: 'BH', name: 'Bahrain' },
    { name: 'BD', name: 'Bangladesh' },
    { name: 'BB', name: 'Barbados' },
    { name: 'BY', name: 'Belarus' },
    { name: 'BE', name: 'Belgium' },
    { name: 'BZ', name: 'Belize' },
    { name: 'BJ', name: 'Benin' },
    { name: 'BT', name: 'Bhutan' },
    { name: 'BO', name: 'Bolivia' },
    { name: 'BA', name: 'Bosnia and Herzegovina' },
    { name: 'BW', name: 'Botswana' },
    { name: 'BN', name: 'Brunei' },
    { name: 'BG', name: 'Bulgaria' },
    { name: 'BF', name: 'Burkina Faso' },
    { name: 'BI', name: 'Burundi' },
    { name: 'CV', name: 'Cabo Verde' },
    { name: 'KH', name: 'Cambodia' },
    { name: 'CM', name: 'Cameroon' },
    { name: 'CF', name: 'Central African Republic' },
    { name: 'TD', name: 'Chad' },
    { name: 'CL', name: 'Chile' },
    { name: 'CO', name: 'Colombia' },
    { name: 'KM', name: 'Comoros' },
    { name: 'CD', name: 'Congo, Democratic Republic of the' },
    { name: 'CG', name: 'Congo, Republic of the' },
    { name: 'CR', name: 'Costa Rica' },
    { name: 'HR', name: 'Croatia' },
    { name: 'CU', name: 'Cuba' },
    { name: 'CY', name: 'Cyprus' },
    { name: 'CZ', name: 'Czech Republic' },
    { name: 'DK', name: 'Denmark' },
    { name: 'DJ', name: 'Djibouti' },
    { name: 'DM', name: 'Dominica' },
    { name: 'DO', name: 'Dominican Republic' },
    { name: 'EC', name: 'Ecuador' },
    { name: 'EG', name: 'Egypt' },
    { name: 'SV', name: 'El Salvador' },
    { name: 'GQ', name: 'Equatorial Guinea' },
    { name: 'ER', name: 'Eritrea' },
    { name: 'EE', name: 'Estonia' },
    { name: 'SZ', name: 'Eswatini' },
    { name: 'ET', name: 'Ethiopia' },
    { name: 'FJ', name: 'Fiji' },
    { name: 'FI', name: 'Finland' },
    { name: 'FR', name: 'France' },
    { name: 'GA', name: 'Gabon' },
    { name: 'GM', name: 'Gambia' },
    { name: 'GE', name: 'Georgia' },
    { name: 'GH', name: 'Ghana' },
    { name: 'GR', name: 'Greece' },
    { name: 'GD', name: 'Grenada' },
    { name: 'GT', name: 'Guatemala' },
    { name: 'GN', name: 'Guinea' },
    { name: 'GW', name: 'Guinea-Bissau' },
    { name: 'GY', name: 'Guyana' },
    { name: 'HT', name: 'Haiti' },
    { name: 'HN', name: 'Honduras' },
    { name: 'HU', name: 'Hungary' },
    { name: 'IS', name: 'Iceland' },
    { name: 'ID', name: 'Indonesia' },
    { name: 'IR', name: 'Iran' },
    { name: 'IQ', name: 'Iraq' },
    { name: 'IE', name: 'Ireland' },
    { name: 'IL', name: 'Israel' },
    { name: 'IT', name: 'Italy' },
    { name: 'JM', name: 'Jamaica' },
    { name: 'JP', name: 'Japan' },
    { name: 'JO', name: 'Jordan' },
    { name: 'KZ', name: 'Kazakhstan' },
    { name: 'KE', name: 'Kenya' },
    { name: 'KI', name: 'Kiribati' },
    { name: 'KW', name: 'Kuwait' },
    { name: 'KG', name: 'Kyrgyzstan' },
    { name: 'LA', name: 'Laos' },
    { name: 'LV', name: 'Latvia' },
    { name: 'LB', name: 'Lebanon' },
    { name: 'LS', name: 'Lesotho' },
    { name: 'LR', name: 'Liberia' },
    { name: 'LY', name: 'Libya' },
    { name: 'LI', name: 'Liechtenstein' },
    { name: 'LT', name: 'Lithuania' },
    { name: 'LU', name: 'Luxembourg' },
    { name: 'MG', name: 'Madagascar' },
    { name: 'MW', name: 'Malawi' },
    { name: 'MY', name: 'Malaysia' },
    { name: 'MV', name: 'Maldives' },
    { name: 'ML', name: 'Mali' },
    { name: 'MT', name: 'Malta' },
    { name: 'MH', name: 'Marshall Islands' },
    { name: 'MR', name: 'Mauritania' },
    { name: 'MU', name: 'Mauritius' },
    { name: 'FM', name: 'Micronesia' },
    { name: 'MD', name: 'Moldova' },
    { name: 'MC', name: 'Monaco' },
    { name: 'MN', name: 'Mongolia' },
    { name: 'ME', name: 'Montenegro' },
    { name: 'MA', name: 'Morocco' },
    { name: 'MZ', name: 'Mozambique' },
    { name: 'MM', name: 'Myanmar (Burma)' },
    { name: 'NA', name: 'Namibia' },
    { name: 'NR', name: 'Nauru' },
    { name: 'NP', name: 'Nepal' },
    { name: 'NL', name: 'Netherlands' },
    { name: 'NZ', name: 'New Zealand' },
    { name: 'NI', name: 'Nicaragua' },
    { name: 'NE', name: 'Niger' },
    { name: 'NG', name: 'Nigeria' },
    { name: 'KP', name: 'North Korea' },
    { name: 'MK', name: 'North Macedonia' },
    { name: 'NO', name: 'Norway' },
    { name: 'OM', name: 'Oman' },
    { name: 'PK', name: 'Pakistan' },
    { name: 'PW', name: 'Palau' },
    { name: 'PS', name: 'Palestine State' },
    { name: 'PA', name: 'Panama' },
    { name: 'PG', name: 'Papua New Guinea' },
    { name: 'PY', name: 'Paraguay' },
    { name: 'PE', name: 'Peru' },
    { name: 'PH', name: 'Philippines' },
    { name: 'PL', name: 'Poland' },
    { name: 'PT', name: 'Portugal' },
    { name: 'QA', name: 'Qatar' },
    { name: 'RO', name: 'Romania' },
    { name: 'RU', name: 'Russia' },
    { name: 'RW', name: 'Rwanda' },
    { name: 'KN', name: 'Saint Kitts and Nevis' },
    { name: 'LC', name: 'Saint Lucia' },
    { name: 'VC', name: 'Saint Vincent and the Grenadines' },
    { name: 'WS', name: 'Samoa' },
    { name: 'SM', name: 'San Marino' },
    { name: 'ST', name: 'Sao Tome and Principe' },
    { name: 'SA', name: 'Saudi Arabia' },
    { name: 'SN', name: 'Senegal' },
    { name: 'RS', name: 'Serbia' },
    { name: 'SC', name: 'Seychelles' },
    { name: 'SL', name: 'Sierra Leone' },
    { name: 'SG', name: 'Singapore' },
    { name: 'SK', name: 'Slovakia' },
    { name: 'SI', name: 'Slovenia' },
    { name: 'SB', name: 'Solomon Islands' },
    { name: 'SO', name: 'Somalia' },
    { name: 'ZA', name: 'South Africa' },
    { name: 'KR', name: 'South Korea' },
    { name: 'SS', name: 'South Sudan' },
    { name: 'ES', name: 'Spain' },
    { name: 'LK', name: 'Sri Lanka' },
    { name: 'SD', name: 'Sudan' },
    { name: 'SR', name: 'Suriname' },
    { name: 'SE', name: 'Sweden' },
    { name: 'CH', name: 'Switzerland' },
    { name: 'SY', name: 'Syria' },
    { name: 'TW', name: 'Taiwan' },
    { name: 'TJ', name: 'Tajikistan' },
    { name: 'TZ', name: 'Tanzania' },
    { name: 'TH', name: 'Thailand' },
    { name: 'TL', name: 'Timor-Leste' },
    { name: 'TG', name: 'Togo' },
    { name: 'TO', name: 'Tonga' },
    { name: 'TT', name: 'Trinidad and Tobago' },
    { name: 'TN', name: 'Tunisia' },
    { name: 'TR', name: 'Turkey' },
    { name: 'TM', name: 'Turkmenistan' },
    { name: 'TV', name: 'Tuvalu' },
    { name: 'UG', name: 'Uganda' },
    { name: 'UA', name: 'Ukraine' },
    { name: 'AE', name: 'United Arab Emirates' },
    { name: 'GB', name: 'United Kingdom' },
    { name: 'UY', name: 'Uruguay' },
    { name: 'UZ', name: 'Uzbekistan' },
    { name: 'VU', name: 'Vanuatu' },
    { name: 'VA', name: 'Vatican City' },
    { name: 'VE', name: 'Venezuela' },
    { name: 'VN', name: 'Vietnam' },
    { name: 'YE', name: 'Yemen' },
    { name: 'ZM', name: 'Zambia' },
    { name: 'ZW', name: 'Zimbabwe' },
];
